import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { t } from '../utils/traductMe';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chronométrage V2 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          chronométrage <a href="https://nextjs.org">.com</a>
        </h1>
        {t('home', 'title')}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by PN-TH
        </a>
      </footer>
    </div>
  );
};

export default Home;
